template_path: app.yaml
parameters:
  Branch: {{ var.branch }}
  PublicSubnet1: !stack_output dev/prerequisites.yaml::PublicSubnet1
  PublicSubnet2: !stack_output dev/prerequisites.yaml::PublicSubnet2
  PublicSubnet3: !stack_output dev/prerequisites.yaml::PublicSubnet3
  PrivateSubnet1: !stack_output dev/prerequisites.yaml::PrivateSubnet1
  PrivateSubnet2: !stack_output dev/prerequisites.yaml::PrivateSubnet2
  PrivateSubnet3: !stack_output dev/prerequisites.yaml::PrivateSubnet3
  MinCapacity: "0"
  MaxCapacity: "3"
  DesiredCapacity: "2"
  AMI: ami-035966e8adab4aaad # ubuntu 18.04
  AssetsBucket: !stack_output dev/prerequisites.yaml::AssetsBucket
  Asset: {{ var.asset }}
  VpcId: !stack_output dev/prerequisites.yaml::VpcId