template_path: prerequisites.yaml
parameters:
  VpcCIDR: 10.0.0.0/16
  PublicSubnet1CIDR: 10.0.0.0/20
  PublicSubnet2CIDR: 10.0.16.0/20
  PublicSubnet3CIDR: 10.0.32.0/20
  PrivateSubnet1CIDR: 10.0.48.0/20
  PrivateSubnet2CIDR: 10.0.64.0/20
  PrivateSubnet3CIDR: 10.0.80.0/20